version: '3.8'
services:
  db:
    container_name: plebdevs-db
    image: postgres:13.2
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - sovereign_network

  app:
    container_name: plebdevs
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    networks:
      - sovereign_network

volumes:
  postgres_data:

networks:
  sovereign_network:
    driver: bridge
